import { ArrowLeft, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { RepChart } from "../components/charts";
import { ConfidenceMeter, ConfirmDialog, Skeleton, useToast } from "../components/Feedback";
import { api, ApiError } from "../lib/api";
import { duration, exLabel, fmtDate, fmtTime, scoreClass } from "../lib/format";
import type { ModelStatus, Rep, Session } from "../lib/types";
import { FAULT_INFO } from "../pose/rules";

const STATUS_TEXT: Record<ModelStatus, string> = {
  ok: "",
  uncertain: "uncertain",
  out_of_distribution: "outside training range",
  not_scored: "not scored",
  unavailable: "model offline",
};

export function ModelCell({ rep }: { rep: Rep }) {
  const st = rep.model_status ?? (rep.model_score === null ? "unavailable" : "ok");
  if (rep.model_score === null || st === "out_of_distribution" || st === "not_scored" || st === "unavailable") {
    const title = st === "out_of_distribution" ? `Features outside the synthetic training range: ${(rep.model_ood ?? []).join(", ")}` : undefined;
    return <span className="muted tiny" title={title}>{STATUS_TEXT[st] || "—"}</span>;
  }
  return (
    <span className={st === "uncertain" ? "muted" : ""} title={st === "uncertain" ? "Model confidence below its validated level" : undefined}>
      {rep.model_score}{st === "uncertain" && <span className="tiny"> ?</span>}
    </span>
  );
}

export default function SessionDetail() {
  const { id } = useParams();
  const nav = useNavigate();
  const toast = useToast();
  const [s, setS] = useState<Session | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [confirm, setConfirm] = useState(false);

  useEffect(() => {
    api<Session>(`/api/sessions/${id}`).then(setS).catch((e: ApiError) => setError(e.message));
  }, [id]);

  async function remove() {
    setConfirm(false);
    try {
      await api(`/api/sessions/${id}`, { method: "DELETE" });
      toast("Session deleted");
      nav("/history");
    } catch (e) {
      toast((e as Error).message, "error");
    }
  }

  if (error) {
    return (
      <div className="page">
        <p className="alert" role="alert">{error}</p>
        <Link to="/history">Back to history</Link>
      </div>
    );
  }
  if (!s) return <div className="page"><Skeleton rows={2} height={32} /><div className="panel"><Skeleton rows={6} /></div></div>;

  const sum = s.summary;
  const reps = s.reps ?? [];
  const f = s.fatigue;
  const unscored = sum?.unscored_reps ?? reps.filter((r) => r.scored === false).length;
  const scoredCount = sum?.scored_reps ?? reps.length - unscored;
  return (
    <div className="page detail">
      <Link to="/history" className="back"><ArrowLeft size={15} /> History</Link>
      <header className="page-head">
        <div>
          <h1>{exLabel(s.exercise)} <span className="h-date">{fmtDate(s.started_at)}, {fmtTime(s.started_at)}</span></h1>
          <p className="sub">
            {s.source === "upload" ? "From an uploaded video" : "Live session"} · {duration(s.duration_s)}
            {s.demo && <span className="tag demo" title="Generated by the seed script, not recorded">demo data</span>}
          </p>
        </div>
        <button className="btn ghost danger" onClick={() => setConfirm(true)}><Trash2 size={15} /> Delete</button>
      </header>
      <ConfirmDialog
        open={confirm} danger title="Delete this session?" confirmLabel="Delete session"
        body="The session and all its reps are removed from your history. This cannot be undone."
        onConfirm={remove} onCancel={() => setConfirm(false)}
      />

      <section className="kpis" aria-label="Summary">
        <div className="kpi"><span>Reps</span><b data-testid="detail-reps">{sum?.total_reps ?? 0}</b></div>
        <div className="kpi"><span>Sets</span><b>{sum?.sets ?? 0}</b></div>
        <div className="kpi"><span>Form score</span><b className={scoreClass(sum?.avg_score)}>{sum?.avg_score ?? "—"}</b></div>
        <div className="kpi" title="Classifier trained on synthetic reps; probability of a clean rep">
          <span>Model score <em className="synthetic">synthetic-trained</em></span><b>{sum?.avg_model_score ?? "—"}</b>
        </div>
        <div className="kpi"><span>Clean / scored</span><b>{sum ? `${sum.clean_reps}/${scoredCount}` : "—"}</b></div>
        <div className="kpi"><span>Tempo down / up</span><b>{sum?.avg_ecc_s?.toFixed(1) ?? "—"}<small> / </small>{sum?.avg_con_s?.toFixed(1) ?? "—"}<small>s</small></b></div>
      </section>

      <section className="panel quality" aria-label="Tracking quality" data-testid="tracking-quality">
        <ConfidenceMeter value={sum?.avg_confidence ?? null} label="Avg tracking" />
        <p className="muted">
          {sum?.avg_confidence === undefined || sum?.avg_confidence === null
            ? "Tracking confidence was not recorded for this session."
            : unscored > 0
              ? `${unscored} of ${reps.length} reps were counted but not scored because the joints were not tracked reliably.`
              : "Every rep was tracked well enough to be scored."}
        </p>
      </section>

      <section className="panel">
        <div className="panel-head">
          <h2>Rep by rep</h2>
          {f && reps.length > 0 && (
            <p className={"fatigue-note" + (f.detected ? " on" : "")} data-testid="fatigue-note">
              {f.detected
                ? `Fatigue from rep ${f.onset_rep}: lift time ${f.slopes.con_s >= 0 ? "+" : ""}${(f.slopes.con_s * 1000).toFixed(0)} ms/rep, range ${f.slopes.rom.toFixed(1)}°/rep.`
                : reps.length < (f.min_reps ?? 6) ? `Fatigue check needs at least ${f.min_reps ?? 6} reps.` : "No clear fatigue: tempo and range held steady."}
            </p>
          )}
        </div>
        {reps.length ? <RepChart reps={reps} onset={f?.detected ? f.onset_rep : null} /> : <p className="empty">No reps were counted in this session.</p>}
      </section>

      <div className="two-col">
        <section className="panel">
          <h2>Sets</h2>
          <table className="table compact">
            <thead><tr><th scope="col">Set</th><th scope="col" className="r">Reps</th><th scope="col" className="r">Avg form</th></tr></thead>
            <tbody>
              {(s.sets ?? []).map((x) => (
                <tr key={x.set}><td>{x.set}</td><td className="r num">{x.reps}</td><td className={"r num " + scoreClass(x.avg_score)}>{x.avg_score ?? "—"}</td></tr>
              ))}
            </tbody>
          </table>
          {sum && sum.top_faults.length > 0 && (
            <>
              <h3>Most frequent</h3>
              <ul className="plain">
                {sum.top_faults.map((t) => (
                  <li key={t.code}><span>{FAULT_INFO[t.code]?.label ?? t.code}</span><span className="num muted">{t.count}×</span></li>
                ))}
              </ul>
            </>
          )}
        </section>
        <section className="panel">
          <h2>Reps</h2>
          <div className="scroll-y">
            <table className="table compact" data-testid="rep-table">
              <thead>
                <tr>
                  <th scope="col">#</th><th scope="col" className="r">Form</th>
                  <th scope="col" className="r" title="Classifier trained on synthetic reps: probability of a clean rep">Model %</th>
                  <th scope="col" className="r" title="Tracking confidence">Conf.</th>
                  <th scope="col" className="r">↓ s</th><th scope="col" className="r">↑ s</th><th scope="col" className="r">ROM</th><th scope="col">Feedback</th>
                </tr>
              </thead>
              <tbody>
                {reps.map((r) => (
                  <tr key={r.i} className={(f?.detected && f.onset_rep && r.i >= f.onset_rep ? "tired " : "") + (r.scored === false ? "unscored" : "")}>
                    <td className="num">{r.i}<span className="muted tiny"> s{r.set}</span></td>
                    <td className={"r num " + scoreClass(r.score)}>{r.score ?? "—"}</td>
                    <td className="r num"><ModelCell rep={r} /></td>
                    <td className="r num">{r.confidence === undefined || r.confidence === null ? "—" : `${Math.round(r.confidence * 100)}%`}</td>
                    <td className="r num">{r.ecc_s.toFixed(1)}</td>
                    <td className="r num">{r.con_s.toFixed(1)}</td>
                    <td className="r num">{Math.round(r.rom)}°</td>
                    <td className="faults-cell">
                      {r.scored === false
                        ? <span className="abstain-line">Not scored: {r.abstain_reason ?? "tracking too weak"}</span>
                        : r.faults.length ? r.faults.map((c) => FAULT_INFO[c]?.label ?? c).join(", ") : <span className="muted">clean</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      </div>
    </div>
  );
}
